name: example
description: A project that showcases how to enable the myple lint for Flutter apps, packages, and plugins.

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

# Add the latest version of `package:myple_lint` as a dev_dependency. The
# lint set provided by this package is activated in the `analysis_options.yaml`
# file located next to this `pubspec.yaml` file.
dev_dependencies:
  myple_lint: # Check https://pub.dev/packages/flutter_lints for latest version number.
