name: linter

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: "0 0 * * 0"
  pull_request:
    branches: [main]
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:
#   PUB_ENVIRONMENT: bot.github

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze .

      - uses: actions/checkout@v2

      - name: Check for sources
        run: |
          filecount=`find lib -name '*.dart' | wc -l`
          if [ $filecount -ne 0 ] || [ -d "bin" ]
          then
            echo 'Dart sources are not allowed in this package!'
            exit 1
          fi

  pana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.5.0

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana
      - name: Verify Pub Score
        run: |
          PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
          echo "score: $PANA_SCORE"
          IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
          if (( $SCORE < $TOTAL )); then echo "minimum score not met!"; exit 1; fi
